// Cross-language validator for the committed static-root-catalog fixture used
// by the Rust `fork-codec` decoder tests
// (crates/fork-codec/testdata/static-root-catalog-wasm32.bin).
//
// IMPORTANT: like the gc_codec and imported-globals descriptors, the
// `kandelo.wpk_fork.static_root_catalog` (KFSR) section has NO TypeScript
// encoder. It is emitted only by the Rust instrumenter
// (`fork_instrument::static_reference_catalog::inject`); the host runtime just
// DECODES its header (`readForkStaticRootCatalogCount` in
// host/src/fork-static-root-catalog.ts). The descriptor is header-only — it
// carries only the harvest-table entry count; per-root identities are recovered
// from the live table export (the deferred engine-floor half). The .bin is
// regenerated by the Rust generator
// (`crates/fork-codec/tests/gen_static_root_catalog_fixture.rs`, run with
// `--ignored`), which drives the REAL encoder over a real two-root module.
//
// This script is the TypeScript half of the cross-language drift guard: it reads
// host/src ONLY, loads the committed section bytes, wraps them into a minimal
// WebAssembly module carrying exactly that one custom section, and decodes them
// with the REAL host decoder. It adds and modifies nothing under host/.
//
// Run with (from repo root):
//   cd host && npx tsx ../crates/fork-codec/testdata/gen-static-root-catalog-fixture.mts

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { readForkStaticRootCatalogCount } from "../../../host/src/fork-static-root-catalog";
import { WPK_FORK_STATIC_ROOT_CATALOG_SECTION } from "../../../host/src/generated/abi";

function uleb128(value: number): number[] {
  const result: number[] = [];
  do {
    let byte = value & 0x7f;
    value >>>= 7;
    if (value !== 0) byte |= 0x80;
    result.push(byte);
  } while (value !== 0);
  return result;
}

/** Append a single custom section to a wasm binary. */
function appendCustomSection(
  wasm: Uint8Array,
  name: string,
  data: Uint8Array,
): Uint8Array {
  const nameBytes = new TextEncoder().encode(name);
  const nameLength = uleb128(nameBytes.byteLength);
  const payloadLength =
    nameLength.length + nameBytes.byteLength + data.byteLength;
  const payload = new Uint8Array(payloadLength);
  payload.set(nameLength);
  payload.set(nameBytes, nameLength.length);
  payload.set(data, nameLength.length + nameBytes.byteLength);
  const sectionSize = uleb128(payload.byteLength);
  const result = new Uint8Array(
    wasm.byteLength + 1 + sectionSize.length + payload.byteLength,
  );
  result.set(wasm);
  let offset = wasm.byteLength;
  result[offset++] = 0; // custom section id
  result.set(sectionSize, offset);
  offset += sectionSize.length;
  result.set(payload, offset);
  return result;
}

const here = dirname(fileURLToPath(import.meta.url));
const binPath = join(here, "static-root-catalog-wasm32.bin");
const section = new Uint8Array(readFileSync(binPath));

const emptyModule = new Uint8Array([0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00]);
const moduleBytes = appendCustomSection(
  emptyModule,
  WPK_FORK_STATIC_ROOT_CATALOG_SECTION,
  section,
);
const module = new WebAssembly.Module(moduleBytes);

const count = readForkStaticRootCatalogCount(module);

console.log(
  JSON.stringify(
    {
      file: binPath,
      byteLength: section.byteLength,
      count,
    },
    null,
    2,
  ),
);
