// Cross-language validator for the committed gc_codec (KFGC) descriptor fixture
// used by the Rust `fork-codec` decoder tests
// (crates/fork-codec/testdata/gc-codec-wasm32.bin).
//
// IMPORTANT: unlike the linked-frame, module-state, and replay-event fixtures,
// the gc_codec descriptor has NO TypeScript encoder. The
// `kandelo.wpk_fork.gc_codec` section is emitted only by the Rust instrumenter
// (`fork_instrument::module_gc_codec::encode_descriptor`); the host runtime just
// DECODES it (`decodeForkGcCodecDescriptor` in host/src/fork-gc-codec.ts). The
// .bin is therefore regenerated by the Rust generator
// (`crates/fork-codec/tests/gen_gc_codec_fixture.rs`, run with `--ignored`),
// which drives the REAL encoder over a real GC-typed module.
//
// This script is the TypeScript half of the cross-language drift guard: it
// reads host/src ONLY, loads the committed bytes, and decodes them with the
// REAL host decoder. If the Rust encoder and the host decoder ever disagree on
// the wire format, this fails; the emitted JSON is the authoritative field-level
// oracle the Rust `fork-codec` decoder asserts against. It adds and modifies
// nothing under host/.
//
// Run with (from repo root):
//   cd host && npx tsx ../crates/fork-codec/testdata/gen-gc-codec-fixture.mts
// (or via scripts/dev-shell.sh if tsx is not otherwise on PATH).

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { decodeForkGcCodecDescriptor } from "../../../host/src/fork-gc-codec";

const here = dirname(fileURLToPath(import.meta.url));
const binPath = join(here, "gc-codec-wasm32.bin");
const bytes = new Uint8Array(readFileSync(binPath));

const descriptor = decodeForkGcCodecDescriptor(bytes);

const layouts = descriptor.layouts.map((layout) => ({
  id: layout.id,
  typeOrdinal: layout.typeOrdinal,
  kind: layout.kind,
  constructor: layout.constructor,
  flags: layout.flags,
  scalarLengthOrStride: layout.scalarLengthOrStride,
  superTypeOrdinal: layout.superTypeOrdinal,
  baseLayoutId: layout.baseLayoutId,
  auxiliary: layout.auxiliary,
  provenanceScalarLength: layout.provenanceScalarLength,
  provenanceReferenceCount: layout.provenanceReferenceCount,
  fields: layout.fields.map((field) => ({
    storage: field.storage,
    flags: field.flags,
    scalarOffset: field.scalarOffset,
    referenceOrdinal: field.referenceOrdinal,
  })),
}));

console.log(
  JSON.stringify(
    {
      file: binPath,
      byteLength: bytes.byteLength,
      layoutCount: layouts.length,
      fieldCount: layouts.reduce((sum, layout) => sum + layout.fields.length, 0),
      layouts,
    },
    null,
    2,
  ),
);
