// Cross-language validator for the committed exception-codec fixture used by
// the Rust `fork-codec` decoder tests
// (crates/fork-codec/testdata/exception-codec-wasm32.bin).
//
// IMPORTANT: like the gc_codec and imported-globals descriptors, the
// `kandelo.wpk_fork.exception_codec` section has NO TypeScript encoder. It is
// emitted only by the Rust instrumenter (`fork_instrument::module_exception_codec`,
// via `replace_descriptor`); the host runtime just DECODES it
// (`readForkExceptionCodecDescriptor` in host/src/fork-exception-provider.ts).
// The .bin is regenerated by the Rust generator
// (`crates/fork-codec/tests/gen_exception_codec_fixture.rs`, run with
// `--ignored`), which drives the REAL encoder over a real three-tag module.
//
// This script is the TypeScript half of the cross-language drift guard: it reads
// host/src ONLY, loads the committed section bytes, wraps them into a minimal
// WebAssembly module carrying exactly that one custom section, and decodes them
// with the REAL host decoder. If the Rust encoder and the host decoder ever
// disagree on the wire format, this fails; the emitted JSON is the authoritative
// field-level oracle the Rust `fork-codec` decoder asserts against. It adds and
// modifies nothing under host/.
//
// Run with (from repo root):
//   cd host && npx tsx ../crates/fork-codec/testdata/gen-exception-codec-fixture.mts
// (or via scripts/dev-shell.sh if tsx is not otherwise on PATH).

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { readForkExceptionCodecDescriptor } from "../../../host/src/fork-exception-provider";
import { WPK_FORK_EXCEPTION_CODEC_SECTION } from "../../../host/src/generated/abi";

function uleb128(value: number): number[] {
  const result: number[] = [];
  do {
    let byte = value & 0x7f;
    value >>>= 7;
    if (value !== 0) byte |= 0x80;
    result.push(byte);
  } while (value !== 0);
  return result;
}

/** Append a single custom section to a wasm binary. */
function appendCustomSection(
  wasm: Uint8Array,
  name: string,
  data: Uint8Array,
): Uint8Array {
  const nameBytes = new TextEncoder().encode(name);
  const nameLength = uleb128(nameBytes.byteLength);
  const payloadLength =
    nameLength.length + nameBytes.byteLength + data.byteLength;
  const payload = new Uint8Array(payloadLength);
  payload.set(nameLength);
  payload.set(nameBytes, nameLength.length);
  payload.set(data, nameLength.length + nameBytes.byteLength);
  const sectionSize = uleb128(payload.byteLength);
  const result = new Uint8Array(
    wasm.byteLength + 1 + sectionSize.length + payload.byteLength,
  );
  result.set(wasm);
  let offset = wasm.byteLength;
  result[offset++] = 0; // custom section id
  result.set(sectionSize, offset);
  offset += sectionSize.length;
  result.set(payload, offset);
  return result;
}

const here = dirname(fileURLToPath(import.meta.url));
const binPath = join(here, "exception-codec-wasm32.bin");
const section = new Uint8Array(readFileSync(binPath));

// Minimal valid module (`\0asm` + version 1) carrying exactly one section.
const emptyModule = new Uint8Array([0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00]);
const moduleBytes = appendCustomSection(
  emptyModule,
  WPK_FORK_EXCEPTION_CODEC_SECTION,
  section,
);
const module = new WebAssembly.Module(moduleBytes);

const descriptor = readForkExceptionCodecDescriptor(module);

console.log(
  JSON.stringify(
    {
      file: binPath,
      byteLength: section.byteLength,
      version: descriptor.version,
      tagCount: descriptor.tags.length,
      tags: descriptor.tags.map((tag) => ({
        tagOrdinal: tag.tagOrdinal,
        layoutId: tag.layoutId,
        scalarByteLength: tag.scalarByteLength,
        referenceCount: tag.referenceCount,
      })),
    },
    null,
    2,
  ),
);
